{
  message: {
    function: 'schemaValidator',
    error: ZodError: [
      {
        "validation": "uuid",
        "code": "invalid_string",
        "message": "El autor debe ser una cadena que represente a un uuid",
        "path": [
          "body",
          "author"
        ]
      }
    ]
        at Object.get error [as error] (C:\Users\Adria\Documents\code\turco\informe5Backend\node_modules\zod\lib\types.js:43:31)
        at ZodObject.parse (C:\Users\Adria\Documents\code\turco\informe5Backend\node_modules\zod\lib\types.js:141:22)
        at C:\Users\Adria\Documents\code\turco\informe5Backend\middlewares\zod.validate.ts:17:14
        at Layer.handle [as handle_request] (C:\Users\Adria\Documents\code\turco\informe5Backend\node_modules\express\lib\router\layer.js:95:5)
        at next (C:\Users\Adria\Documents\code\turco\informe5Backend\node_modules\express\lib\router\route.js:144:13)
        at complete (C:\Users\Adria\Documents\code\turco\informe5Backend\node_modules\passport\lib\middleware\authenticate.js:271:13)
        at C:\Users\Adria\Documents\code\turco\informe5Backend\node_modules\passport\lib\middleware\authenticate.js:278:15
        at pass (C:\Users\Adria\Documents\code\turco\informe5Backend\node_modules\passport\lib\authenticator.js:428:14)
        at Authenticator.transformAuthInfo (C:\Users\Adria\Documents\code\turco\informe5Backend\node_modules\passport\lib\authenticator.js:450:5)
        at C:\Users\Adria\Documents\code\turco\informe5Backend\node_modules\passport\lib\middleware\authenticate.js:275:22 {
      issues: [
        {
          validation: 'uuid',
          code: 'invalid_string',
          message: 'El autor debe ser una cadena que represente a un uuid',
          path: [ 'body', 'author' ]
        }
      ],
      addIssue: [Function (anonymous)],
      addIssues: [Function (anonymous)],
      errors: [
        {
          validation: 'uuid',
          code: 'invalid_string',
          message: 'El autor debe ser una cadena que represente a un uuid',
          path: [ 'body', 'author' ]
        }
      ]
    }
  },
  level: 'error'
}
{
  message: {
    function: 'schemaValidator',
    error: ZodError: [
      {
        "validation": "uuid",
        "code": "invalid_string",
        "message": "El autor debe ser una cadena que represente a un uuid",
        "path": [
          "body",
          "author"
        ]
      }
    ]
        at Object.get error [as error] (C:\Users\Adria\Documents\code\turco\informe5Backend\node_modules\zod\lib\types.js:43:31)
        at ZodObject.parse (C:\Users\Adria\Documents\code\turco\informe5Backend\node_modules\zod\lib\types.js:141:22)
        at C:\Users\Adria\Documents\code\turco\informe5Backend\middlewares\zod.validate.ts:17:14
        at Layer.handle [as handle_request] (C:\Users\Adria\Documents\code\turco\informe5Backend\node_modules\express\lib\router\layer.js:95:5)
        at next (C:\Users\Adria\Documents\code\turco\informe5Backend\node_modules\express\lib\router\route.js:144:13)
        at complete (C:\Users\Adria\Documents\code\turco\informe5Backend\node_modules\passport\lib\middleware\authenticate.js:271:13)
        at C:\Users\Adria\Documents\code\turco\informe5Backend\node_modules\passport\lib\middleware\authenticate.js:278:15
        at pass (C:\Users\Adria\Documents\code\turco\informe5Backend\node_modules\passport\lib\authenticator.js:428:14)
        at Authenticator.transformAuthInfo (C:\Users\Adria\Documents\code\turco\informe5Backend\node_modules\passport\lib\authenticator.js:450:5)
        at C:\Users\Adria\Documents\code\turco\informe5Backend\node_modules\passport\lib\middleware\authenticate.js:275:22 {
      issues: [
        {
          validation: 'uuid',
          code: 'invalid_string',
          message: 'El autor debe ser una cadena que represente a un uuid',
          path: [ 'body', 'author' ]
        }
      ],
      addIssue: [Function (anonymous)],
      addIssues: [Function (anonymous)],
      errors: [
        {
          validation: 'uuid',
          code: 'invalid_string',
          message: 'El autor debe ser una cadena que represente a un uuid',
          path: [ 'body', 'author' ]
        }
      ]
    }
  },
  level: 'error'
}
{
  message: {
    function: 'DatabaseHandler.FindById',
    error: PrismaClientKnownRequestError: 
    Invalid `prisma.users.findUniqueOrThrow()` invocation:
    
    
    Can't reach database server at `127.0.0.1`:`3306`
    
    Please make sure your database server is running at `127.0.0.1`:`3306`.
        at zr.handleRequestError (C:\Users\Adria\Documents\code\turco\informe5Backend\node_modules\@prisma\client\runtime\library.js:122:8308)
        at zr.handleAndLogRequestError (C:\Users\Adria\Documents\code\turco\informe5Backend\node_modules\@prisma\client\runtime\library.js:122:7697)
        at zr.request (C:\Users\Adria\Documents\code\turco\informe5Backend\node_modules\@prisma\client\runtime\library.js:122:7307)
        at C:\Users\Adria\Documents\code\turco\informe5Backend\node_modules\@prisma\client\runtime\library.js:112:550 {
      code: 'P1001',
      clientVersion: '5.0.0',
      meta: { database_host: '127.0.0.1', database_port: 3306 }
    }
  },
  level: 'error'
}
{
  message: {
    function: 'AuthService.jwtLoginVerify',
    error: TypeError: Cannot use 'in' operator to search for 'username' in null
        at AuthService.<anonymous> (C:\Users\Adria\Documents\code\turco\informe5Backend\auth\auth.service.ts:66:23)
        at Generator.next (<anonymous>)
        at fulfilled (C:\Users\Adria\Documents\code\turco\informe5Backend\auth\auth.service.ts:5:58)
  },
  level: 'error'
}
{
  message: {
    function: 'DatabaseHandler.FindById',
    error: PrismaClientKnownRequestError: 
    Invalid `prisma.users.findUniqueOrThrow()` invocation:
    
    
    Can't reach database server at `127.0.0.1`:`3306`
    
    Please make sure your database server is running at `127.0.0.1`:`3306`.
        at zr.handleRequestError (C:\Users\Adria\Documents\code\turco\informe5Backend\node_modules\@prisma\client\runtime\library.js:122:8308)
        at zr.handleAndLogRequestError (C:\Users\Adria\Documents\code\turco\informe5Backend\node_modules\@prisma\client\runtime\library.js:122:7697)
        at zr.request (C:\Users\Adria\Documents\code\turco\informe5Backend\node_modules\@prisma\client\runtime\library.js:122:7307)
        at C:\Users\Adria\Documents\code\turco\informe5Backend\node_modules\@prisma\client\runtime\library.js:112:550 {
      code: 'P1001',
      clientVersion: '5.0.0',
      meta: { database_host: '127.0.0.1', database_port: 3306 }
    }
  },
  level: 'error'
}
{
  message: {
    function: 'AuthService.jwtLoginVerify',
    error: TypeError: Cannot use 'in' operator to search for 'username' in null
        at AuthService.<anonymous> (C:\Users\Adria\Documents\code\turco\informe5Backend\auth\auth.service.ts:66:23)
        at Generator.next (<anonymous>)
        at fulfilled (C:\Users\Adria\Documents\code\turco\informe5Backend\auth\auth.service.ts:5:58)
  },
  level: 'error'
}
{
  message: {
    function: 'DatabaseHandler.FindById',
    error: PrismaClientInitializationError: 
    Invalid `prisma.users.findUniqueOrThrow()` invocation:
    
    
    Can't reach database server at `127.0.0.1`:`3306`
    
    Please make sure your database server is running at `127.0.0.1`:`3306`.
        at zr.handleRequestError (C:\Users\Adria\Documents\code\turco\informe5Backend\node_modules\@prisma\client\runtime\library.js:122:8581)
        at zr.handleAndLogRequestError (C:\Users\Adria\Documents\code\turco\informe5Backend\node_modules\@prisma\client\runtime\library.js:122:7697)
        at zr.request (C:\Users\Adria\Documents\code\turco\informe5Backend\node_modules\@prisma\client\runtime\library.js:122:7307)
        at C:\Users\Adria\Documents\code\turco\informe5Backend\node_modules\@prisma\client\runtime\library.js:112:550 {
      clientVersion: '5.0.0',
      errorCode: undefined
    }
  },
  level: 'error'
}
{
  message: {
    function: 'DatabaseHandler.FindById',
    error: PrismaClientInitializationError: 
    Invalid `prisma.users.findUniqueOrThrow()` invocation:
    
    
    Can't reach database server at `127.0.0.1`:`3306`
    
    Please make sure your database server is running at `127.0.0.1`:`3306`.
        at zr.handleRequestError (C:\Users\Adria\Documents\code\turco\informe5Backend\node_modules\@prisma\client\runtime\library.js:122:8581)
        at zr.handleAndLogRequestError (C:\Users\Adria\Documents\code\turco\informe5Backend\node_modules\@prisma\client\runtime\library.js:122:7697)
        at zr.request (C:\Users\Adria\Documents\code\turco\informe5Backend\node_modules\@prisma\client\runtime\library.js:122:7307)
        at C:\Users\Adria\Documents\code\turco\informe5Backend\node_modules\@prisma\client\runtime\library.js:112:550 {
      clientVersion: '5.0.0',
      errorCode: undefined
    }
  },
  level: 'error'
}
{
  message: {
    function: 'AuthService.localLoginVerify',
    error: PrismaClientInitializationError: 
    Invalid `this.prisma.users.findUniqueOrThrow()` invocation in
    C:\Users\Adria\Documents\code\turco\informe5Backend\auth\auth.service.ts:40:106
    
      37 },
      38 public localLoginVerify = async (req: Request, username: string, password: string, done: DoneType) => {
      39   try {
    â†’ 40     const user: Prisma.UsersCreateInput | Prisma.UsersUncheckedCreateInput = await this.prisma.users.findUniqueOrThrow(
    Can't reach database server at `127.0.0.1`:`3306`
    
    Please make sure your database server is running at `127.0.0.1`:`3306`.
        at zr.handleRequestError (C:\Users\Adria\Documents\code\turco\informe5Backend\node_modules\@prisma\client\runtime\library.js:122:8581)
        at zr.handleAndLogRequestError (C:\Users\Adria\Documents\code\turco\informe5Backend\node_modules\@prisma\client\runtime\library.js:122:7697)
        at zr.request (C:\Users\Adria\Documents\code\turco\informe5Backend\node_modules\@prisma\client\runtime\library.js:122:7307)
        at C:\Users\Adria\Documents\code\turco\informe5Backend\node_modules\@prisma\client\runtime\library.js:112:550 {
      clientVersion: '5.0.0',
      errorCode: undefined
    }
  },
  level: 'error'
}
{
  message: {
    function: 'AuthService.jwtLoginVerify',
    error: TypeError: Cannot use 'in' operator to search for 'username' in null
        at AuthService.<anonymous> (C:\Users\Adria\Documents\code\turco\informe5Backend\auth\auth.service.ts:68:23)
        at Generator.next (<anonymous>)
        at fulfilled (C:\Users\Adria\Documents\code\turco\informe5Backend\auth\auth.service.ts:5:58)
  },
  level: 'error'
}
{
  message: {
    function: 'AuthService.jwtLoginVerify',
    error: TypeError: Cannot use 'in' operator to search for 'username' in null
        at AuthService.<anonymous> (C:\Users\Adria\Documents\code\turco\informe5Backend\auth\auth.service.ts:68:23)
        at Generator.next (<anonymous>)
        at fulfilled (C:\Users\Adria\Documents\code\turco\informe5Backend\auth\auth.service.ts:5:58)
  },
  level: 'error'
}
